<Project Sdk="Dalamud.NET.Sdk/15.0.0">
    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <Import Project="..\LLib\LLib.targets"/>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="6.0.4">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
        <PackageReference Include="xunit" Version="2.9.3" />
        <PackageReference Include="xunit.runner.visualstudio" Version="3.0.2">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <!-- Need to be explicitly added for test projects, as it otherwise won't find the DLLs -->
    <ItemGroup>
        <Reference Include="Dalamud"/>
        <Reference Include="Lumina"/>
        <Reference Include="Lumina.Excel"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Gearsetter\Gearsetter.csproj"/>
    </ItemGroup>
</Project>