<Project Sdk="Dalamud.NET.Sdk/15.0.0">
    <PropertyGroup>
        <Version>4.3</Version>
		<TargetFramework>net10.0-windows7.0</TargetFramework>
        <OutputPath>dist</OutputPath>
    </PropertyGroup>

    <Import Project="..\LLib\LLib.targets" />
    <Import Project="..\LLib\RenameZip.targets" />

    <ItemGroup>
        <ProjectReference Include="..\LLib\LLib.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="lootSources.json" />
      <EmbeddedResource Include="lootSources.json">
          <LogicalName>Gearsetter.LootSources</LogicalName>
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="System.Text.Json" Version="10.0.7" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Update="DotNet.ReproducibleBuilds" Version="2.0.2" />
      <PackageReference Update="Microsoft.SourceLink.Gitea" Version="10.0.203" />
    </ItemGroup>
</Project>
